apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-071de2ab9ccf31337
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-deployment-dev
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
    spec:
      containers:
        - name: container-1
          image: nginx
          volumeMounts:
            - name: static-volume
              mountPath: "/usr/share/nginx/html"

      volumes:
        - name: static-volume
          PersistentVolumeClaim:
            claimName: static-volume
          
   
