apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-071de2ab9ccf31337
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
spec:
  storageClassName: "" # prevent default StorageClass
  volumeName: static-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-deployment-dev
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1d   # must match EBS volume AZ
      containers:
        - name: container-1
          image: nginx
          volumeMounts:
            - name: static-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-service
  labels:
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
