---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-sc-dynamic"
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    environment: dev
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: roboshop-efs-dynamic
            mountPath: /usr/share/nginx/html
      volumes:
      - name: roboshop-efs-dynamic
        persistentVolumeClaim:
          claimName: roboshop-efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
  labels:
    environment: dev
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

