apiVersion: v1
kind: PersistentVolume
metadata:
  name: roboshop-efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f0c3676d652c7dfd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    environment: dev
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: roboshop-efs-static
            mountPath: /usr/share/nginx/html
      volumes:
      - name: roboshop-efs-static
        persistentVolumeClaim:
          claimName: roboshop-efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-service
  labels:
    environment: dev
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: roboshop
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

