---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-Service
  labels:
    project: roboshop
    environment: dev
spec:
  slector:
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-dev-1
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
  template:
    metadata:
      project: roboshop
      environment: dev
    spec:
      containers:
        - name: roboshop-container-1
          image: nginx
          

