---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-headless
  labels:
    project: roboshop
    environment: dev
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-normal
  labels:
    project: roboshop
    environment: dev
spec:
  ports:
  - port: 80
    name: web
  selector:
    project: roboshop
    environment: dev
---  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
  serviceName: "nginx-svc-headless"
  replicas: 3 
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: dynamic-volume
          mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
        name: dynamic-volume

        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "roboshop-ebs-sc"
          resources:
            requests:
              storage: 1Gi
